# Generated by Django 4.1.7 on 2023-06-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0014_remove_work_user_work_user'),
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='MUser',
        ),
    ]
