# Generated by Django 4.1.7 on 2023-06-23 06:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Auth', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_id', models.CharField(max_length=20, null=True)),
                ('work_heading', models.CharField(default='default_work_desc_<django.db.models.fields.CharField>', max_length=100, null=True)),
                ('work_desc', models.CharField(default='default_work_desc_<django.db.models.fields.CharField>', max_length=200, null=True)),
                ('work_location', models.CharField(default='default_work_location_<django.db.models.fields.CharField>', max_length=100, null=True)),
                ('work_amount', models.CharField(default='₹ 0 /-', max_length=50, null=True)),
                ('work_reciept', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), null=True, size=None)),
                ('added_at', models.CharField(default='-', max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('MUser', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Auth.muser')),
            ],
        ),
    ]
