# Generated by Django 4.1.7 on 2023-06-10 08:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Field', '0002_work_work_amount_alter_work_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='work',
            name='user',
        ),
        migrations.AddField(
            model_name='work',
            name='User',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
