# Generated by Django 4.1.7 on 2023-06-17 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Field', '0016_work_added_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='work',
            name='added_at',
            field=models.CharField(default='-', max_length=50, null=True),
        ),
    ]
